import { Router } from "express";
import ConversationController from "~/controllers/conversation.controller";
import DependencyInjection from '~/di/di';
const router = Router();
const conversationController = DependencyInjection.get<ConversationController>(ConversationController);
router.post("/", conversationController.getOrCreateConversation);
router.delete("/", conversationController.deleteConversation);
router.get("/", conversationController.getConversations);
router.get("/id", conversationController.getConversationById);
router.post("/message", conversationController.sendMessage);
export default router;